blank_issues_enabled: false
contact_links:
  - name: âš ï¸ Application issue
    url: https://github.com/jmir1/aniyomi/issues/new/choose
    about: Issues and requests about the app itself should be opened in the tachiyomi repository instead
  - name: ğŸ“¦ Aniyomi extensions
    url: https://aniyomi.jmir.xyz/extensions
    about: List of all available extensions with download links
  - name: ğŸ–¥ï¸ Aniyomi website
    url: https://aniyomi.jmir.xyz/help/
    about: Common questions are answered here.
  - name: Aniyomi app GitHub repository
    url: https://github.com/jmir1/aniyomi
    about: Issues about the app itself should be opened here instead.
