blank_issues_enabled: false
contact_links:
  - name: âš ï¸ Application issue
    url: https://github.com/aniyomiorg/aniyomi/issues/new/choose
    about: Issues and requests about the app itself should be opened in the tachiyomi repository instead
  - name: ğŸ“¦ Aniyomi extensions
    url: https://aniyomi.org/extensions
    about: List of all available extensions with download links
  - name: ğŸ–¥ï¸ Aniyomi website
    url: https://aniyomi.org/help/
    about: Guides, troubleshooting, and answers to common questions
  - name: Aniyomi app GitHub repository
    url: https://github.com/aniyomiorg/aniyomi
    about: Issues about the app itself should be opened here instead.
